apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapp
  labels:
    app: dapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dapp
  template:
    metadata:
      labels:
        app: dapp
    spec:
      containers:
      - name: dapp
        image: alsgh458/dapp
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        
---

        
apiVersion: v1
kind: Service
metadata:
  name: dapp
spec:
  selector:
    app: dapp
  ports:
    - name: dapp-endpoint
      port: 8080
      protocol: TCP
      targetPort: 8080


